# Copyright 2019 Decipher Technology Studios
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2

defaults: &defaults
  working_directory: /usr/local/src/gm-authenticator-plugins
  docker:
    - image: golang:1.12.5-alpine3.9

jobs:
  vendor:
    <<: *defaults
    steps:
      - run: apk add --no-cache ca-certificates git make openssh
      - run: mkdir -p ~/.ssh && ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ .Revision }}
            - cache-{{ .Branch }}
            - cache
      - run: make vendor
      - save_cache:
          key: cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - vendor
      - persist_to_workspace:
          root: /usr/local/src/gm-authenticator-plugins
          paths:
            - vendor
  test:
    <<: *defaults
    steps:
      - run: apk add --no-cache ca-certificates git make openssh
      - run: mkdir -p ~/.ssh && ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - checkout
      - attach_workspace:
          at: /usr/local/src/gm-authenticator-plugins
      - run: make test

workflows:
  version: 2
  default:
    jobs:
      - vendor:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /.*/
      - test:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /.*/
          requires:
            - vendor
