version: 2

defaults: &defaults
  working_directory: /usr/local/src/gm-authenticator-plugins
  docker:
    - image: golang:1.12.5-alpine3.9

jobs:
  vendor:
    <<: *defaults
    steps:
      - run: apk add --no-cache ca-certificates git make openssh
      - run: mkdir -p ~/.ssh && ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ .Revision }}
            - cache-{{ .Branch }}
            - cache
      - run: make vendor
      - save_cache:
          key: cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - vendor
      - persist_to_workspace:
          root: /usr/local/src/gm-authenticator-plugins
          paths:
            - vendor
  test:
    <<: *defaults
    steps:
      - run: apk add --no-cache ca-certificates git make openssh
      - run: mkdir -p ~/.ssh && ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - checkout
      - attach_workspace:
          at: /usr/local/src/gm-authenticator-plugins
      - run: make test

workflows:
  version: 2
  default:
    jobs:
      - vendor:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /.*/
      - test:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /.*/
          requires:
            - vendor
